In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')
df.head(3)

    brand  km_driven    fuel         owner  selling_price
0  Maruti     145500  Diesel   First Owner         450000
1   Skoda     120000  Diesel  Second Owner         370000
2   Honda     140000  Petrol   Third Owner         158000

In [4]:
print(df['fuel'].nunique())
print(df['owner'].nunique())

4
5

## OneHotEncoding Using Pandas

### 1. One Hot Encoding on K columns
here I only transfer fuel and owner
so change the fule column replace with put 4 different column of n unique values and samely change owner column and replace with 5 different column of n unique values

In [5]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### 2. One Hot Encoding on K-1 columns
because their a problem occur if we use linear model like linear regression which called multicolinearlity problem

In [6]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## Don't use Pandas One Hot Encoding
Pandas function get_dummies() can't fixed the order of the columns so it's prefer to use scikit learn One Hot Encoding function in ML projects

## Scikit Learn One Hot Encoding (Prefered)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   str
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   str
 3   owner          8128 non-null   str
 4   selling_price  8128 non-null   int64
dtypes: int64(2), str(3)
memory usage: 317.6 KB